### ISSUE TITLE
Error 1.8 version

### ISSUE THREAD

**Issue by TheHallowed** [Skungee/Skungee-2.0.0#102]
[Skungee] Charset US-ASCII does not support some symbols in script /home/container/plugins/Skript/scripts/Teste.sk
[01:07:39 WARN]: java.nio.charset.MalformedInputException: Input length = 1
[01:07:39 WARN]:        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
[01:07:39 WARN]:        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
[01:07:39 WARN]:        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[01:07:39 WARN]:        at java.io.InputStreamReader.read(InputStreamReader.java:184)
[01:07:39 WARN]:        at java.io.BufferedReader.fill(BufferedReader.java:161)
[01:07:39 WARN]:        at java.io.BufferedReader.readLine(BufferedReader.java:324)
[01:07:39 WARN]:        at java.io.BufferedReader.readLine(BufferedReader.java:389)
[01:07:39 WARN]:        at java.nio.file.Files.readAllLines(Files.java:3205)
[01:07:39 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.lambda$getScripts$0(ServerDataTask.java:53)
[01:07:39 WARN]:        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[01:07:39 WARN]:        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[01:07:39 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.getScripts(ServerDataTask.java:47)
[01:07:39 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.access$200(ServerDataTask.java:27)
[01:07:39 WARN]:        at com.skungee.spigot.tasks.ServerDataTask$2.toJson(ServerDataTask.java:88)
[01:07:39 INFO]: [TuSKe] Checking for latest update...
[01:07:39 WARN]:        at com.skungee.japson.shared.Japson.lambda$sendPacket$4(Japson.java:183)
[01:07:39 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[01:07:39 WARN]:        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[01:07:39 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[01:07:39 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[01:07:39 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[01:07:39 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

**Comment by TheLimeGlass** [comment]
You can try setting the charset to Cp1252 which usually supports most symbols.
