### ISSUE TITLE
Can't enable plugin

### ISSUE THREAD

**Issue by DarkBoy2005** [Skungee/Skungee-2.0.0#105]
## Description
I tried to install Skungee on my server. Everything was working fine until I restarted the server. On the proxy server the plugin was able to lunch but on the lobby server it couldn't.

## Screenshots or Errors
```
>....[13:38:18 INFO]: [Skungee] Enabling Skungee v2.0.0-BETA-2
>....[13:38:18 ERROR]: Error occurred while enabling Skungee v2.0.0-BETA-2 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'javassist.d javassist.f.a(javassist.d)' the class loader org.bukkit.plugin.java.PluginClassLoader @38ff3d37 of the current class, com/skungee/spigot/SpigotSkungeeL10, and the class loader org.bukkit.plugin.java.PluginClassLoader @39c6473d for the method's defining class, javassist/f, have different Class objects for the type javassist/d used in the signature (com.skungee.spigot.SpigotSkungeeL10 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @38ff3d37, parent loader 'app'; javassist.f is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @39c6473d, parent loader 'app')
at com.skungee.spigot.SpigotSkungeeL10.a(Unknown Source) ~[?:?]
at com.skungee.spigot.SpigotSkungee.onEnable(SpigotSkungee.java) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
[13:38:18 INFO]: [Skungee] Disabling Skungee v2.0.0-BETA-2at java.lang.Thread.run(Thread.java:831) [?:?]
>....
>....[13:38:18 ERROR]: Error occurred while disabling Skungee v2.0.0-BETA-2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.skungee.japson.client.JapsonClient.shutdown()" because "this.japson" is null
at com.skungee.spigot.SpigotSkungee.onDisable(SpigotSkungee.java:99) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

## Actual Behavior
Not starting and crashing the plugin

## Expected Behavior
Starting just fine

## Steps to Reproduce the Problem
1. Get the latest purpur version for 1.16.5
2. Install the latest skungee and skript on it and on a bungee server
3. Restart the servers

## Specifications
Skungee Version: 2.0.0-BETA 1
Proxy Platform and Version: AegisNormal-v9.2.1
System/Panel (if applicable): Ubuntu 20.08 with Java 16. Server running with help of PufferPanel
Lobby server version: Purpur 1.16.5-1171

**Comment by TheLimeGlass** [comment]
Try redownloading from https://github.com/Skungee/Skungee-2.0.0/releases/tag/2.0.0-BETA-2

**Comment by TheLimeGlass** [comment]
Do you have two Skungee jars in the plugin folder?

**Comment by DarkBoy2005** [comment]
> 
> 
> Try redownloading from https://github.com/Skungee/Skungee-2.0.0/releases/tag/2.0.0-BETA-2

I tried, it didn't work...

**Comment by DarkBoy2005** [comment]
> 
> 
> Do you have two Skungee jars in the plugin folder?

I only have one. Currently I'm using a older version and it works.
