### ISSUE TITLE
connect and signal bug

### ISSUE THREAD

**Issue by bckd00r** [Skungee/Skungee-2.0.0#107]
The plugin needs a bone version to be more successful and dealing with bugs is a waste of time, please don't post the plugin broken until you can determine that it's fully fixed.

## Steps to Reproduce the Problem
1. "connect player server" does not work inside the function.
2. "signal" it does not work and cannot be executed in any way
3. Command usage in a player on a proxy can sometimes get confused (commands used and players get mixed up)

## Specifications
Skungee 2.0.0-beta2
FlameCord(lates)
Minecraft PuPur(1.17.1)
System/Panel (if applicable):

I think the plugin will be more usable if these 3 big problems can be fixed. I'm waiting for a new update as soon as possible. -greeting

**Comment by TheLimeGlass** [comment]
Need errors. Send code.

**Comment by bckd00r** [comment]
[21:06:11 ERROR]: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: unresolved address
[21:06:11 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
[21:06:11 ERROR]:       at com.skungee.japson.shared.Japson.sendPacket(Japson.java:176)
[21:06:11 ERROR]:       at com.skungee.japson.shared.Japson.sendPacket(Japson.java:147)
[21:06:11 ERROR]:       at com.skungee.proxy.handlers.SignalHandler.execute(SignalHandler.java:50)
[21:06:11 ERROR]:       at com.skungee.japson.shared.Executor.handle(Executor.java:24)
[21:06:11 ERROR]:       at com.skungee.japson.server.SocketHandler.lambda$run$1(SocketHandler.java:58)
[21:06:11 ERROR]:       at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[21:06:11 ERROR]:       at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[21:06:11 ERROR]:       at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728)
[21:06:11 ERROR]:       at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[21:06:11 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[21:06:11 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[21:06:11 ERROR]:       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[21:06:11 ERROR]:       at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[21:06:11 ERROR]:       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[21:06:11 ERROR]:       at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[21:06:11 ERROR]:       at com.skungee.japson.server.SocketHandler.run(SocketHandler.java:60)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:06:11 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[21:06:11 ERROR]: Caused by: java.lang.IllegalArgumentException: unresolved address
[21:06:11 ERROR]:       at java.base/java.net.DatagramPacket.setSocketAddress(DatagramPacket.java:358)
[21:06:11 ERROR]:       at java.base/java.net.DatagramPacket.<init>(DatagramPacket.java:165)
[21:06:11 ERROR]:       at java.base/java.net.DatagramPacket.<init>(DatagramPacket.java:210)
[21:06:11 ERROR]:       at com.skungee.japson.shared.Japson.lambda$sendPacket$4(Japson.java:163)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:06:11 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by bckd00r** [comment]
My port forwardings are at factory settings.
