### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by juzijun233** [Skungee/Skungee-2.0.0#127]
## Description
Unable to run bungee command

## Screenshots or Errors
```
#!#! 
[22:12:32 ERROR]: #!#! [Skript] Severe Error:
[22:12:32 ERROR]: #!#! Could not load bctest.sk
[22:12:32 ERROR]: #!#! 
[22:12:32 ERROR]: #!#! Something went horribly wrong with Skript.
[22:12:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:12:32 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:12:32 ERROR]: #!#! Here is full list of them:
[22:12:32 ERROR]: #!#! skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) Skungee v2.0.0-BETA-2 Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/) Floodgate-Skript v2.1 skScraft v1.5 
[22:12:32 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:12:32 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:12:32 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:12:32 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:12:32 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:12:32 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:12:32 ERROR]: #!#! 
[22:12:32 ERROR]: #!#! Stack trace:
[22:12:32 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[22:12:32 ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1060)
[22:12:32 ERROR]: #!#!     at !S[脚本]-Skript[2.6.1].jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[22:12:32 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:12:32 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[22:12:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2344)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2155)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2136)
[22:12:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[22:12:32 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[22:12:32 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:12:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[22:12:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1450)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[22:12:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1428)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1421)
[22:12:32 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1399)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1310)
[22:12:32 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[22:12:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[22:12:32 ERROR]: #!#! 
[22:12:32 ERROR]: #!#! Version Information:
[22:12:32 ERROR]: #!#!   Skript: 2.6.1 (latest)
[22:12:32 ERROR]: #!#!     Flavor: skriptlang-github
[22:12:32 ERROR]: #!#!     Date: 22:18:42.554713200
[22:12:32 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[22:12:32 ERROR]: #!#!   Minecraft: 1.17.1
[22:12:32 ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12-LTS)
[22:12:32 ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[22:12:32 ERROR]: #!#! 
[22:12:32 ERROR]: #!#! Server platform: Paper
[22:12:32 ERROR]: #!#! 
[22:12:32 ERROR]: #!#! Current node: execute bungee proxy command "/skins set %command sender% _2000120519991203" (bctest.sk, line 3)
[22:12:32 ERROR]: #!#! Current item: null
[22:12:32 ERROR]: #!#! 
[22:12:32 ERROR]: #!#! Thread: Server thread
[22:12:32 ERROR]: #!#! 
[22:12:32 ERROR]: #!#! Language: english
[22:12:32 ERROR]: #!#! Link parse mode: DISABLED
[22:12:32 ERROR]: #!#! 
[22:12:32 ERROR]: #!#! End of Error.
[22:12:32 ERROR]: #!#! 
```

debug mod on ↓
```
Skungee] Enabling Skungee v2.0.0-BETA-2
[22:33:19] [Server thread/INFO]: [com.skungee.japson.shared.Japson] Started Japson client bound to kubernetes.docker.internal:8000.
[22:33:19] [Server thread/INFO]: [Skungee] Started on kubernetes.docker.internal/127.0.0.1:8000
[22:33:19] [Server thread/INFO]: [com.skungee.japson.shared.Japson] Started Japson server bound to kubernetes.docker.internal:1000.
[22:33:19] [Server thread/WARN]: [Skungee] Loaded class org.slf4j.impl.StaticLoggerBinder from Triton v3.7.3 which is not a depend, softdepend or loadbefore of this plugin.
[22:33:19] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 35 ms to scan 1 urls, producing 2 keys and 5 values 
[22:33:19] [Server thread/INFO]: [Skungee] has been enabled!


## Actual Behavior


## Expected Behavior


## Steps to Reproduce the Problem
1.
2.
3.

## Specifications
Skungee Version: 2.0.0-beta2
Proxy Platform and Version: waterfall-1.18-480
System/Panel (if applicable):windows

**Comment by juzijun233** [comment]
```
Skript] Loaded 20 variables in 0.0 seconds
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:33:26] [Server thread/ERROR]: #!#! Could not load bctest.sk
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[22:33:26] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:33:26] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:33:26] [Server thread/ERROR]: #!#! Here is full list of them:
[22:33:26] [Server thread/ERROR]: #!#! skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) Skungee v2.0.0-BETA-2 Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/) Floodgate-Skript v2.1 skScraft v1.5 
[22:33:26] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:33:26] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:33:26] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:33:26] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:33:26] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:33:26] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! Stack trace:
[22:33:26] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for citizen
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[22:33:26] [Server thread/ERROR]: #!#!     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.lang.Statement.parse(Statement.java:61)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1113)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.command.Commands.loadCommand(Commands.java:489)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:707)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[22:33:26] [Server thread/ERROR]: #!#!     at !S[�ű�]-Skript[2.6.1].jar//ch.njol.skript.Skript$1.run(Skript.java:778)
[22:33:26] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:33:26] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:33:26] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1242)
[22:33:26] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[22:33:26] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! Version Information:
[22:33:26] [Server thread/ERROR]: #!#!   Skript: 2.6.1 (latest)
[22:33:26] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[22:33:26] [Server thread/ERROR]: #!#!     Date: 22:18:42.554713200
[22:33:26] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[22:33:26] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[22:33:26] [Server thread/ERROR]: #!#!   Java: 17.0.1 (OpenJDK 64-Bit Server VM 17.0.1+12-LTS)
[22:33:26] [Server thread/ERROR]: #!#!   OS: Windows Server 2019 amd64 10.0
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! Server platform: Paper
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! Current node: execute bungee proxy command "skins set %command sender% _2000120519991203" (bctest.sk, line 3)
[22:33:26] [Server thread/ERROR]: #!#! Current item: null
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! Thread: Server thread
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! Language: english
[22:33:26] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/ERROR]: #!#! End of Error.
[22:33:26] [Server thread/ERROR]: #!#! 
[22:33:26] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[22:33:26] [Server thread/INFO]: [Skript] Loaded 2 scripts with a total of 2 triggers and 2 commands in 0.12 seconds
[22:33:26] [Server thread/INFO]: [Skript] Finished loading.
```

**Comment by juzijun233** [comment]
```
[com.skungee.japson.shared.Japson] Started Japson client bound to kubernetes.docker.internal:8000.
[09:51:55] [Server thread/INFO]: [Skungee] Started on kubernetes.docker.internal/127.0.0.1:8000
[09:51:55] [Server thread/WARN]: java.net.BindException: Address already in use: bind
[09:51:55] [Server thread/WARN]: 	at java.base/sun.nio.ch.Net.bind0(Native Method)
[09:51:55] [Server thread/WARN]: 	at java.base/sun.nio.ch.Net.bind(Net.java:555)
[09:51:55] [Server thread/WARN]: 	at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194)
[09:51:55] [Server thread/WARN]: 	at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164)
[09:51:55] [Server thread/WARN]: 	at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:107)
[09:51:55] [Server thread/WARN]: 	at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1426)
[09:51:55] [Server thread/WARN]: 	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:330)
[09:51:55] [Server thread/WARN]: 	at !Skript-Addon[蹦极]-Skungee-2.0.0-BETA-2.jar//com.skungee.japson.server.JapsonServer.<init>(JapsonServer.java:52)
[09:51:55] [Server thread/WARN]: 	at !Skript-Addon[蹦极]-Skungee-2.0.0-BETA-2.jar//com.skungee.japson.server.JapsonServer.<init>(JapsonServer.java:38)
[09:51:55] [Server thread/WARN]: 	at !Skript-Addon[蹦极]-Skungee-2.0.0-BETA-2.jar//com.skungee.spigot.SpigotSkungee.onEnable(SpigotSkungee.java:64)
[09:51:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:51:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:51:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[09:51:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[09:51:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[09:51:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736)
[09:51:55] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:353)
[09:51:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1233)
[09:51:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[09:51:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[09:51:56] [Server thread/INFO]: [Skungee] has been enabled!
```

**Comment by TheLimeGlass** [comment]
The first error is Skellett

The second error is because you're binding to a port that is already in use.
