### ISSUE TITLE
cant get the server connect to work

### ISSUE THREAD

**Issue by patritha** [Skungee/Skungee-2.0.0#149]
## What you need help with
the code i wrote didnt teleport me to but instead errored me

t
## What you've tried so far
i changed the ports for the plugin and i gave this error instead of doing nothing (what it did before i changed he ports)

[21:52:32 INFO]: TrumpetsRlife issued server command: /s authlobby
[21:52:34 WARN]: java.util.concurrent.TimeoutException
[21:52:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
[21:52:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
[21:52:34 WARN]:        at Skungee-2.0.0-BETA-4.jar//com.skungee.japson.shared.Japson.sendPacket(Japson.java:176)
[21:52:34 WARN]:        at Skungee-2.0.0-BETA-4.jar//com.skungee.japson.client.JapsonClient.sendPacket(JapsonClient.java:137)
[21:52:34 WARN]:        at Skungee-2.0.0-BETA-4.jar//com.skungee.spigot.elements.effects.EffConnect.execute(EffConnect.java:51)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:286)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:251)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:256)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:261)
[21:52:34 WARN]:        at Skript.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:178)
[21:52:34 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[21:52:34 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[21:52:34 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:52:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678)
[21:52:34 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2466)
[21:52:34 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2245)
[21:52:34 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:52:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:52:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:52:34 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1386)
[21:52:34 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[21:52:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:52:34 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1363)
[21:52:34 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1356)
[21:52:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[21:52:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1334)
[21:52:34 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1219)
[21:52:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308)
[21:52:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

my code

command /s <string>:
     trigger:
          set {s} to arg-1
          set {p} to player's name
          send players "{p}" to server "{s}"

## Specifications
Skungee Version: 2.0.0-BETA-4
Proxy Platform and Version: bungeecord idk version
System/Panel (if applicable): windows 10

**Comment by TheLimeGlass** [comment]
`send players "%{p}%" to server "%{s}%"`

**Comment by patritha** [comment]
thanks for the help but it still does nothing
