### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by YodaZen** [Skungee/Skungee-2.0.0#150]
[21:06:10 ERROR]: Error occurred while enabling Skungee v2.0.0-BETA-4 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'javassist.d javassist.f.a(javassist.d)' the class loader 'Skungee-2.0.0-BETA-4.jar' @28176182 of the current class, com/skungee/spigot/SpigotSkungeeL10, and the class loader 'TimTheEnchanter.jar' @1906125 for the method's defining class, javassist/f, have different Class objects for the type javassist/d used in the signature (com.skungee.spigot.SpigotSkungeeL10 is in unnamed module of loader 'Skungee-2.0.0-BETA-4.jar' @28176182, parent loader 'app'; javassist.f is in unnamed module of loader 'TimTheEnchanter.jar' @1906125, parent loader 'app')
        at com.skungee.spigot.SpigotSkungeeL10.a(Unknown Source) ~[Skungee-2.0.0-BETA-4.jar:?]
        at com.skungee.spigot.SpigotSkungee.onEnable(SpigotSkungee.java) ~[Skungee-2.0.0-BETA-4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:06:10 INFO]: [Skungee] Disabling Skungee v2.0.0-BETA-4
[21:06:10 ERROR]: Error occurred while disabling Skungee v2.0.0-BETA-4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.skungee.japson.client.JapsonClient.shutdown()" because "this.japson" is null
        at com.skungee.spigot.SpigotSkungee.onDisable(SpigotSkungee.java:102) ~[Skungee-2.0.0-BETA-4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]

**Comment by TheLimeGlass** [comment]
Requires Java 17
