### ISSUE TITLE
What is bind, and how use it?

### ISSUE THREAD

**Issue by ItsDoome12** [Skungee/Skungee-2.0.0#151]
## What you need help with
`[20:39:57 ERROR]: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: unresolved address
[20:39:57 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
[20:39:57 ERROR]:       at com.skungee.japson.shared.Japson.sendPacket(Japson.java:176)
[20:39:57 ERROR]:       at com.skungee.japson.shared.Japson.sendPacket(Japson.java:147)
[20:39:57 ERROR]:       at com.skungee.proxy.handlers.SignalHandler.execute(SignalHandler.java:50)
[20:39:57 ERROR]:       at com.skungee.japson.shared.Executor.handle(Executor.java:24)
[20:39:57 ERROR]:       at com.skungee.japson.server.SocketHandler.lambda$run$1(SocketHandler.java:58)
[20:39:57 ERROR]:       at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[20:39:57 ERROR]:       at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[20:39:57 ERROR]:       at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728)
[20:39:57 ERROR]:       at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[20:39:57 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[20:39:57 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[20:39:57 ERROR]:       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[20:39:57 ERROR]:       at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[20:39:57 ERROR]:       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:39:57 ERROR]:       at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[20:39:57 ERROR]:       at com.skungee.japson.server.SocketHandler.run(SocketHandler.java:60)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:39:57 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[20:39:57 ERROR]: Caused by: java.lang.IllegalArgumentException: unresolved address
[20:39:57 ERROR]:       at java.base/java.net.DatagramPacket.setSocketAddress(DatagramPacket.java:358)
[20:39:57 ERROR]:       at java.base/java.net.DatagramPacket.<init>(DatagramPacket.java:165)
[20:39:57 ERROR]:       at java.base/java.net.DatagramPacket.<init>(DatagramPacket.java:210)
[20:39:57 ERROR]:       at com.skungee.japson.shared.Japson.lambda$sendPacket$4(Japson.java:163)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:39:57 ERROR]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[20:40:08 ERROR]: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: unresolved address
[20:40:08 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[20:40:08 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
[20:40:08 ERROR]:       at com.skungee.japson.shared.Japson.sendPacket(Japson.java:176)
[20:40:08 ERROR]:       at com.skungee.japson.shared.Japson.sendPacket(Japson.java:147)
[20:40:08 ERROR]:       at com.skungee.proxy.handlers.SignalHandler.execute(SignalHandler.java:50)
[20:40:08 ERROR]:       at com.skungee.japson.shared.Executor.handle(Executor.java:24)
[20:40:08 ERROR]:       at com.skungee.japson.server.SocketHandler.lambda$run$1(SocketHandler.java:58)
[20:40:08 ERROR]:       at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[20:40:08 ERROR]:       at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[20:40:08 ERROR]:       at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728)
[20:40:08 ERROR]:       at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[20:40:08 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[20:40:08 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[20:40:08 ERROR]:       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[20:40:08 ERROR]:       at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[20:40:08 ERROR]:       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:40:08 ERROR]:       at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[20:40:08 ERROR]:       at com.skungee.japson.server.SocketHandler.run(SocketHandler.java:60)
[20:40:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:40:08 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:40:08 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)`

Its error, and

`[20:37:28 WARN]: java.net.BindException: Address already in use: bind
[20:37:28 WARN]:        at java.base/sun.nio.ch.Net.bind0(Native Method)
[20:37:28 WARN]:        at java.base/sun.nio.ch.Net.bind(Net.java:555)
[20:37:28 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194)
[20:37:28 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164)
[20:37:28 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:107)
[20:37:28 WARN]:        at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1426)
[20:37:28 WARN]:        at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:330)
[20:37:28 WARN]:        at Skungee-2.0.0-BETA-4.jar//com.skungee.japson.server.JapsonServer.<init>(JapsonServer.java:52)
[20:37:28 WARN]:        at Skungee-2.0.0-BETA-4.jar//com.skungee.japson.server.JapsonServer.<init>(JapsonServer.java:38)
[20:37:28 WARN]:        at Skungee-2.0.0-BETA-4.jar//com.skungee.spigot.SpigotSkungee.onEnable(SpigotSkungee.java:66)
[20:37:28 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:37:28 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[20:37:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502)
[20:37:28 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535)
[20:37:28 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449)
[20:37:28 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725)
[20:37:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[20:37:28 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212)
[20:37:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[20:37:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

how fix it?

## Specifications
Skungee Version: Skungee-2.0.0-BETA-4
Proxy Platform and Version: WaterFall and Paper
System/Panel (if applicable):

**Comment by TheLimeGlass** [comment]
The address of the machine that hosts the proxy like bungeecord.
