### ISSUE TITLE
Proxy players do not work & Can't set a network variable to another variable ..

### ISSUE THREAD

**Issue by ardaok** [Skungee/Skungee-2.0.0#3]
%proxied players% or %proxy players% return <none>
I can not check if a network variable is set or not
I can't set a network variable to another variable

```
[11:01:37 ERROR]: #!#!
[11:01:37 ERROR]: #!#! Stack trace:
[11:01:37 ERROR]: #!#! java.lang.NullPointerException
[11:01:37 ERROR]: #!#!     at com.skungee.spigot.elements.expressions.ExprNetworkVariable.change(ExprNetworkVariable.java:130)
[11:01:37 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
[11:01:37 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[11:01:37 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[11:01:37 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[11:01:37 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[11:01:37 ERROR]: #!#!     at me.iblitzkriegi.vixio.events.base.BaseEvent.lambda$null$1(BaseEvent.java:139)
[11:01:37 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[11:01:37 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[11:01:37 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
[11:01:37 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[11:01:37 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[11:01:37 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[11:01:37 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[11:01:37 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[11:01:37 ERROR]: #!#!
[11:01:37 ERROR]: #!#! Version Information:
[11:01:37 ERROR]: #!#!   Skript: 2.5-alpha5 (latest)
[11:01:37 ERROR]: #!#!     Flavor: skriptlang-github
[11:01:37 ERROR]: #!#!     Date: 2020-07-02
[11:01:37 ERROR]: #!#!   Bukkit: 1.16.1-R0.1-SNAPSHOT
[11:01:37 ERROR]: #!#!   Minecraft: 1.16.1
[11:01:37 ERROR]: #!#!   Java: 1.8.0_252 (OpenJDK 64-Bit Server VM 25.252-b09)
[11:01:37 ERROR]: #!#!   OS: Linux amd64 4.19.62-mod-std-ipv6-64-rescue
[11:01:37 ERROR]: #!#!
[11:01:37 ERROR]: #!#! Server platform: Paper
[11:01:37 ERROR]: #!#!
[11:01:37 ERROR]: #!#! Current node: null
[11:01:37 ERROR]: #!#! Current item: set network variable to {dcode::%{_kod}(as java.lang.Object)%}(as java.lang.Object)
[11:01:37 ERROR]: #!#! Current trigger: guild message received seen by "Vision Integration" (on guild message received seen by "Vision Integration":) (Discord.sk, line 294)
[11:01:37 ERROR]: #!#!
[11:01:37 ERROR]: #!#! Thread: Server thread
[11:01:37 ERROR]: #!#!
[11:01:37 ERROR]: #!#! Language: english
[11:01:37 ERROR]: #!#! Link parse mode: STRICT
[11:01:37 ERROR]: #!#!
[11:01:37 ERROR]: #!#! End of Error.
[11:01:37 ERROR]: #!#!
```

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.0-ALPHA-6
