### ISSUE TITLE
Cache returning null

### ISSUE THREAD

**Issue by Hypenexy** [Skungee/Skungee-2.0.0#32]
## Description
Everything I try to use has errors and is not working.

## Screenshots or Errors
This is using the example in the releases.

[17:16:55 INFO]: Hypenexy [e1741604-94bf-4b3d-a9d0-cda0106abd00]: /players lobby
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! [Skript] Severe Error:
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! Something went horribly wrong with Skript.
[17:16:58 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:16:58 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:16:58 ERROR]: #!#! Here is full list of them:
[17:16:58 ERROR]: #!#! skRayFall v1.9.21 (https://sk.rayfall.net/) SkBee v1.5.2 (https://github.com/ShaneBeee/SkBee) skDragon v0.16 skUtilities v0.9.2 (https://tim740.github.io/) Skungee v2.0.0-ALPHA-6 SkQuery v4.1.3
[17:16:58 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[17:16:58 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:16:58 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:16:58 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:16:58 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:16:58 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! Stack trace:
[17:16:58 ERROR]: #!#! com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key lobby.
[17:16:58 ERROR]: #!#!     at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2463)
[17:16:58 ERROR]: #!#!     at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2425)
[17:16:58 ERROR]: #!#!     at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[17:16:58 ERROR]: #!#!     at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[17:16:58 ERROR]: #!#!     at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
[17:16:58 ERROR]: #!#!     at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
[17:16:58 ERROR]: #!#!     at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
[17:16:58 ERROR]: #!#!     at com.skungee.spigot.managers.ServerManager.getServer(ServerManager.java:62)
[17:16:58 ERROR]: #!#!     at com.skungee.spigot.objects.SkungeeServerMapper.apply(SkungeeServerMapper.java:15)
[17:16:58 ERROR]: #!#!     at com.skungee.spigot.elements.DefaultConverters$2.convert(DefaultConverters.java:32)
[17:16:58 ERROR]: #!#!     at com.skungee.spigot.elements.DefaultConverters$2.convert(DefaultConverters.java:28)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:391)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:166)
[17:16:58 ERROR]: #!#!     at com.skungee.spigot.elements.expressions.ExprProxyPlayers.get(ExprProxyPlayers.java:41)
[17:16:58 ERROR]: #!#!     at com.skungee.spigot.elements.expressions.ExprProxyPlayers.get(ExprProxyPlayers.java:20)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.iterator(SimpleExpression.java:313)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.lang.Loop.walk(Loop.java:79)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:249)
[17:16:58 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:166)
[17:16:58 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[17:16:58 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[17:16:58 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:16:58 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1895)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1714)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[17:16:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[17:16:58 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! Version Information:
[17:16:58 ERROR]: #!#!   Skript: 2.5-beta3 (latest)
[17:16:58 ERROR]: #!#!     Flavor: skriptlang-github
[17:16:58 ERROR]: #!#!     Date: 2020-08-28
[17:16:58 ERROR]: #!#!   Bukkit: 1.16.2-R0.1-SNAPSHOT
[17:16:58 ERROR]: #!#!   Minecraft: 1.16.2
[17:16:58 ERROR]: #!#!   Java: 1.8.0_261 (Java HotSpot(TM) 64-Bit Server VM 25.261-b12)
[17:16:58 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! Server platform: Paper
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! Current node: null
[17:16:58 ERROR]: #!#! Current item: loop proxied players
[17:16:58 ERROR]: #!#! Current trigger: command /players (simple event) (list.sk, line -1)
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! Thread: Server thread
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! Language: english
[17:16:58 ERROR]: #!#! Link parse mode: DISABLED
[17:16:58 ERROR]: #!#!
[17:16:58 ERROR]: #!#! End of Error.
[17:16:58 ERROR]: #!#!

## Specifications
Skungee Version: 2.0.0 Alpha 7
Proxy Platform and Version: Bungeecord latest as of 7/9/2020 and Paper 136

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.0-ALPHA-9
