### ISSUE TITLE
java.io.EOFException & java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by Chsui** [Skungee/Skungee-2.0.0#65]
```
 java.util.concurrent.TimeoutException
[13:59:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
[13:59:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
[13:59:13 WARN]:        at com.sitrica.japson.shared.Japson.sendPacket(Japson.java:200)
[13:59:13 WARN]:        at com.sitrica.japson.client.JapsonClient.sendPacket(JapsonClient.java:150)
[13:59:13 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.run(ServerDataTask.java:65)
[13:59:13 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[13:59:13 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:59:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:59:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[13:59:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[13:59:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

I uninstalled the existing 1.0.15 version and installed the 2.0.0 ALPHA-14 version. Since I turned on the server, I keep getting the above error.

I just put Skungee into the Bungee server plugins folder and each server's plugins folder. Is my installation method wrong? Or is it Skungee's problem?

```
14:08:02 [SEVERE] Exception in thread "pool-2-thread-1"
14:08:02 [SEVERE] java.lang.IllegalStateException: java.io.EOFException
14:08:02 [SEVERE]     at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408)
14:08:02 [SEVERE]     at com.sitrica.japson.server.SocketHandler.run(SocketHandler.java:45)
14:08:02 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
14:08:02 [SEVERE]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
14:08:02 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:834)
14:08:02 [SEVERE] Caused by: java.io.EOFException
14:08:02 [SEVERE]     at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
14:08:02 [SEVERE]     at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
14:08:02 [SEVERE]     at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
14:08:02 [SEVERE]     at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406)
14:08:02 [SEVERE]     ... 4 more
```

I'm also getting this error on Bungee's console.

Skungee 2.0.0 ALPHA-14
BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT
Paper 1.16.4 b416

**Comment by TheLimeGlass** [comment]
The  packet was incorrectly sent or was not a Skungee packet.

Make sure the versions are the same on the Spigot and Proxy side.
