### ISSUE TITLE
Migrated host - network variable issue (pterodactyl)

### ISSUE THREAD

**Issue by tandpfun** [Skungee/Skungee-2.0.0#74]
## What you need help with & what I've tried
Hi! I migrated hosts to a VPS using pterodactyl, and I got everything working, but I get `[Skungee] Timed out attempting to send network variable {variabletest}` when trying to get/set a variable. Everything bound correctly, and I gave the different servers their needed ports. I am using 0.0.0.0 (as that's the only thing that worked, and I saw to use that in another thread). 

With debug mode, I see this:
```
[11:35:51 INFO]: Sent non-returnable packet with id 8 and data {"japson-address":"0.0.0.0","japson-port":6532,"limit":50,"version":"git-PaperSpigot-\"4c7641d\" (MC: 1.8.8)","address":"0.0.0.0","motd":"HUB 1","port":25566,"whitelisted":[],"banned":[],"operators":["4937c81e-6437-4d65-af10-0b75ee9ba053"],"receiver-port":6533}
```

I was using alpha-9 but I switched to alpha-17 and started getting this error:
```
[11:49:18 INFO]: [Skungee] Charset US-ASCII does not support some symbols in script /home/container/plugins/Skript/scripts/hub.sk
[11:49:18 WARN]: java.nio.charset.MalformedInputException: Input length = 1
[11:49:18 WARN]:        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
[11:49:18 WARN]:        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
[11:49:18 WARN]:        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[11:49:18 WARN]:        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
[11:49:18 WARN]:        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
[11:49:18 WARN]:        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
[11:49:18 WARN]:        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
[11:49:18 WARN]:        at java.base/java.nio.file.Files.readAllLines(Files.java:3333)
[11:49:18 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.lambda$getScripts$0(ServerDataTask.java:53)
[11:49:18 WARN]:        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[11:49:18 WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[11:49:18 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.getScripts(ServerDataTask.java:47)
[11:49:18 WARN]:        at com.skungee.spigot.tasks.ServerDataTask.access$200(ServerDataTask.java:27)
[11:49:18 WARN]:        at com.skungee.spigot.tasks.ServerDataTask$2.toJson(ServerDataTask.java:88)
[11:49:18 WARN]:        at com.skungee.japson.shared.Japson.lambda$sendPacket$4(Japson.java:183)
[11:49:18 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
[11:49:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

Proxy config: https://ptero.co/xidovuroli.yml
Server config: https://ptero.co/asufacalap.yml

I think it's unrelated, but I would like to know what I should do. What version should I use, and what could cause the variables not to work?

Thank you so much!

## Specifications
Skungee Version: v2.0.0-ALPHA-17
Proxy Platform and Version: BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:830ee8f:1556
System/Panel (if applicable): Pterodactyl & Paper 1.8.8 for the servers.

**Comment by MennoGamed** [comment]
Hey,
I have the same problem. 

I have found this on the internet: https://github.com/Skungee/Skungee/issues/32
I just don't get any wiser from this either.

**Comment by ThunderScripts** [comment]
try setting 

global-scripts:
    # The charset to send the scripts to the Spigot Skungee as.
    # See https://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html
    charset: "UTF-8"

**Comment by tandpfun** [comment]
That probably solves the second issue, but not the first

**Comment by TheLimeGlass** [comment]
The debug packet being sent is healthy

**Comment by tandpfun** [comment]
> The debug packet being sent is healthy

Hmm, is there some config I'm missing, or some wrong port binding or something? I'll send my full logs later.

**Comment by TheLimeGlass** [comment]
It should be fine if that error isn't happening anymore.

**Comment by tandpfun** [comment]
> It should be fine if that error isn't happening anymore.

Wdym? I still get the failed to send var error. Here are my new configs & logs:
Server: https://ptero.co/ozisebisum.yml
Proxy: https://ptero.co/exinerimug.yml

Server Logs: https://ptero.co/qixutajupo.log
Proxy Logs: https://ptero.co/uhokatahoj.log

**Comment by TheLimeGlass** [comment]
global scripts disabled in alpha 18 for the time being

**Comment by tandpfun** [comment]
@TheLimeGlass That probably fixed my other issues, but I just tested and I'm still unable to send the network variables, which is the original issue.

**Comment by tandpfun** [comment]
Probably something to do with the servers sending the wrong IP to the proxy. Is there any way for me to set the exact ip/ports to use to communicate with the proxy?

**Comment by TheLimeGlass** [comment]
Please make a new issue highlighting the variables and provide the packet debug of the sending and receiving on Spigot and Proxy

**Comment by tandpfun** [comment]
> Please make a new issue highlighting the variables and provide the packet debug of the sending and receiving on Spigot and Proxy, hastebin or raw markup

#78
