### ISSUE TITLE
Issue with global variables

### ISSUE THREAD

**Issue by dergrosehd** [Skungee/Skungee-2.0.0#83]
I have a problem with global variables
My code is
`command /sktestbungee [<number>]:
	trigger:
		if arg 1 is set:
			set network variable {sktestbungee::%player%} to "%arg-1%"
			set action bar of player to "%arg-1%"
			stop
		else:
			send "%{sktestbungee::%player%}%"`
And the error log is
`[07:54:53 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.2-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1181) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.lang.Variable.getName()Lch/njol/skript/lang/VariableString;
        at com.skungee.spigot.elements.expressions.ExprNetworkVariable.change(ExprNetworkVariable.java:124) ~[?:?]
        at ch.njol.skript.effects.EffChange.execute(EffChange.java:273) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:54) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:269) ~[?:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:164) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 17 more
[07:54:53 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_292]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 5 more`
Can anyone help me?

**Comment by TheLimeGlass** [comment]
What version of Skungee are you use?
Did the Proxy Skungee connect? Enable debug mode on the Skungee Proxy and Skungee Spigot to see if there are messages about it connecting proper.

**Comment by dergrosehd** [comment]
I have the version 2.0.0-ALPHA-20
They all connect
When I activate the debug mode every second about 10 times this message comes "[18:36:36] [pool-6-thread-1/INFO] [com.skungee.japson.shared.Japson]: Returning data {"success":true} as packet id 0".

**Comment by TheLimeGlass** [comment]
The debug message is normal and supposed to be sent.

**Comment by TheLimeGlass** [comment]
Error is unrelated to connection issues. @dergrosehd

**Comment by TheLimeGlass** [comment]
Issue caused by outdated Skript version.
