### ISSUE TITLE
Console Errors (Waterfall & Spigot)

### ISSUE THREAD

**Issue by SniperTVmc** [Skungee/Skungee-2.0.0#84]
### I have these errors with the latest version of Skungee2.0

**Error on Spigot:**
> [17:24:17 ERROR]: Could not load 'plugins\Skungee-2.0.0-ALPHA-21.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/skungee/spigot/SpigotSkungee has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>         at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
> Caused by: java.lang.UnsupportedClassVersionError: com/skungee/spigot/SpigotSkungee has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_301]
>         at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
>         at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
>         at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
>         at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_301]
>         at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_301]
>         at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_301]
>         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_301]
>         at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
>         at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301]
>         at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_301]
>         at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 6 more

**Error on Waterfall:**
> [17:25:55 WARN]: Error loading plugin Skungee
java.lang.UnsupportedClassVersionError: com/skungee/bungeecord/BungeeSkungee has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_301]
>         at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
>         at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
>         at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
>         at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
>         at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
>         at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
>         at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
>         at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
>         at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
>         at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]

**Comment by TheLimeGlass** [comment]
Update to Java 16
